
  
@url = http://localhost:3022 

### show all users 
GET {{url}} 
content-type: application/json

### delete user 
DELETE  {{url}}/deleteuser/618ff8342f581f201adc2be3
content-type: application/json

### insert user 
POST  {{url}}/adduser
content-type: application/json

{
	"user": {
		"name": "Angie Additive",
		"username": "angie_additive",
		"email": "angie@hotmail.de"
	}
}

### edit user 
PATCH  {{url}}/edituser/618ff8342f581f201adc2be3
content-type: application/json

{
	"email": "2222@gmail.com"
}